#!/bin/sh

timestamp="$(date +%Y-%m-%d_%H:%M:%S)"
targetbase="$HOME/Pictures/screenshots"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1
scrot $targetbase/$timestamp.png

echo "Screenshot saved on $HOME/Pictures/screenshots/$targetbase/$timestamp"
